name: gotcha
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: 0.9.13+1
  firebase_auth: 0.8.4+5
  image_picker: 0.6.0+1
  firebase_core: 0.3.4
  googleapis: ^0.53.0
  googleapis_auth: 0.2.7
  flutter_vlc_player: 0.0.2
  firebase_storage: 2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.7.0

flutter:
  uses-material-design: true
  
  assets:
    #- assets/george_credentials.json
    - defaultUser.png
    - user-placeholder.png
    - furry_george.jpg
    - gotcha.png
    - lib/data/img/gotcha_placeholder.png
    - gotcha_signin.png
    - gosnellgod.png

flutter_icons:
  android: "launcher_icon"
  image_path: "assests/gotcha.png"